stages:
  data_ingestion:
    cmd: python src/datas/data_ingestion.py
    deps:
      - src/datas/data_ingestion.py
    outs:
      - data/raw
    
  data_preprocessing:
    cmd: python src/datas/data_preprocessing.py
    deps: 
      - src/datas/data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed
    outs:
      - data/interim
      - models/vector.joblib
      - models/resampler.joblib

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/interim
    outs:
      - models/LGBMClassifier.joblib
    
    