
name: ci_workflows

on: push

jobs:
  run_dvc_pipeline:
    runs-on: ubuntu-latest
    steps: 
      - name: code checkout
        uses: actions/checkout@v3
      
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run_pipeline 
        env:
          PULSECORE_PAT: ${{secrets.PULSECORE_PAT}}
          PULSECORE_USERNAME: ${{secrets.PULSECORE_USERNAME}}
        run: |
          dvc repro


      # - name: Push DVC-tracked data to remote
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_PC }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PC }}
      #     AWS_DEFAULT_REGION: eu-north-1  # Replace with your AWS region
      #   run: |
      #     dvc push

      # - name: Configure Git
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # - name: Add changes to Git
      #   run: |
      #     git add .

      # - name: Commit changes
      #   if: ${{ github.actor != 'github-actions[bot]' }}
      #   run: |
      #     git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"

      # - name: Push changes
      #   if: ${{ github.actor != 'github-actions[bot]' }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git push origin ${{ github.ref_name }}

  
      - name: Model testing
        env:
          PULSECORE_PAT: ${{secrets.PULSECORE_PAT}}
          PULSECORE_USERNAME: ${{secrets.PULSECORE_USERNAME}}
        
        run: |
          python tests/model_testing.py

      - name: Model Promotion to Production
        if: success()
        env:
          PULSECORE_PAT: ${{secrets.PULSECORE_PAT}}
          PULSECORE_USERNAME: ${{secrets.PULSECORE_USERNAME}}
        run: |
          python scripts/model_promotion.py   


      - name: API Testing
        env:
          PULSECORE_PAT: ${{secrets.PULSECORE_PAT}}
          PULSECORE_USERNAME: ${{secrets.PULSECORE_USERNAME}}
        # export PYTHONPATH=$PWD adding current directory as part of the module search path.
        run: |
          export PYTHONPATH=$PWD 
          pytest tests/test_app.py tests/test_services.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACESS_KEY_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          aws-region: eu-north-1
      
      - name: Login to aws ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 128529977235.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build docker image
        run: |
          docker build -t pulsecore_dockerimg_repo .

      - name: Tag Docker image
        run: |
          docker tag pulsecore_dockerimg_repo:latest 128529977235.dkr.ecr.eu-north-1.amazonaws.com/pulsecore_dockerimg_repo:latest
      
      - name: push image to ECR
        run: | 
          docker push 128529977235.dkr.ecr.eu-north-1.amazonaws.com/pulsecore_dockerimg_repo:latest

      - name: Create .env file
        if: success()
        run: |
          cat > .env << EOF
          YOUTUBEAPI_KEY=${{ secrets.PULSECORE_YT_API }}
          PULSECORE_PAT=${{ secrets.PULSECORE_PAT }}
          PULSECORE_USERNAME=${{ secrets.PULSECORE_USERNAME }}
          EOF

      - name: Create deployment bundle
        if: success()
        run: |
          zip -r deployment.zip appspec.yml deploy .env

      - name: Upload deployment bundle to S3
        if: success()
        run: |
          aws s3 cp deployment.zip s3://pulsecoreappdeploymentscript/deployment.zip

      - name: Trigger CodeDeploy deployment
        if: success()
        run: |
          aws deploy create-deployment \
            --application-name mypulsecoreapp \
            --deployment-group-name mypulsecoreappdeploymentgroup \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=pulsecoreappdeploymentscript,key=deployment.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --region eu-north-1
              
        
        




